### ISSUE TITLE
OSC Listener does not open UDP port and Learn Binding throws "prompt() is not supported"

### ISSUE THREAD

**Issue by Alberto-Aguilar-UCR** [riskcapital/ghost-arcade#5]
# OSC Listener Does Not Start / Configured UDP Port Never Opens + Learn Binding Throws `prompt()` Error

## Summary

The OSC Listener section appears in the Ghost Arcade desktop application and allows manual OSC bindings to be created. However, the OSC listener does not appear to actually start.

The configured UDP port is never opened, and OSC messages sent to the configured address and port are not received or processed by the application.

Additionally, the **+ Learn Binding** option throws a JavaScript error indicating that `prompt()` is not supported in the current Electron context.

---

## Environment

* App: Ghost Arcade
* Platform: Windows
* Executable: `C:\Program Files\Ghost-Arcade\Ghost-Arcade.exe`
* OSC Port: `8000`
* Mobile Control Port: `9001`

---

## Steps to Reproduce

1. Open Ghost Arcade.
2. Navigate to the **OSC** section.
3. Configure the OSC port as `8000`.
4. Create a manual OSC binding:

   * OSC Address: `/preset/0`
   * Param Path: `map:preset:0`
5. Send an OSC message to the configured address and port.
6. Verify whether Ghost Arcade opens the configured UDP port.

---

## Expected Behavior

Ghost Arcade should start listening for OSC messages on the configured UDP port.

For example, Windows should show an active UDP listener on port `8000`:

```text
UDP    0.0.0.0:8000    *:*
```

or:

```text
UDP    127.0.0.1:8000  *:*
```

After receiving an OSC message for `/preset/0`, the mapped parameter path `map:preset:0` should be triggered.

---

## Actual Behavior

Ghost Arcade does not appear to open the configured OSC UDP port.

The following commands show no UDP listener on port `8000`:

```powershell
netstat -ano | findstr :8000
netstat -ano -p UDP | findstr :8000
Get-NetUDPEndpoint -LocalPort 8000
```

Sending OSC messages to the configured address and port does not trigger the mapped preset.

---

## Additional Observation

The Mobile Control server starts correctly and opens TCP port `9001`:

```text
TCP    0.0.0.0:9001           0.0.0.0:0              LISTENING
```

This suggests that Ghost Arcade is able to create network sockets normally and that the issue may be specific to the OSC listener implementation.

---

## Learn Binding Error

When attempting to use **+ Learn Binding**, Ghost Arcade logs the following error:

```json
[
  {
    "timestamp": "2026-06-19T22:15:31.219Z",
    "message": "Uncaught Error: prompt() is not supported.",
    "stack": "Error: prompt() is not supported.\n    at ht.__click (file:///C:/Program%20Files/Ghost-Arcade/resources/app.asar/dist/assets/App-1HEdG5EZ.js:3257:16635)\n    at HTMLDivElement.Jr (file:///C:/Program%20Files/Ghost-Arcade/resources/app.asar/dist/assets/main-DMnSKtMx.js:2:26502)",
    "source": "file:///C:/Program%20Files/Ghost-Arcade/resources/app.asar/dist/assets/main-DMnSKtMx.js:2:26633"
  }
]
```

This appears to indicate that the Learn Binding UI is attempting to call `prompt()`, but `prompt()` is unavailable in the current Electron runtime context.

---

## Impact

This prevents Ghost Arcade from being controlled externally via OSC tools, including:

* TouchOSC
* Lemur
* TouchDesigner
* DAWs with OSC support
* Custom OSC controllers and automation tools

At present, both manual OSC bindings and the Learn Binding workflow appear non-functional, making the OSC integration unusable.

**Comment by Hphone123** [comment]
I had the same issue on MacOS 15 with GhostArcade 1.9.95. The UDP port was not opened, and the "'prompt()' is not supported" error was thrown if I wanted to use "+ Learn". However, after some time, this issue disappeared (i'd say roughly an hour, but I did not time it, and cannot reproduce it now, since it's just working), and I was able to recieve OSC messages. I did not edit my system's settings or reboot. I did restart GhostArcade a few times, but the issue did not disappear immediately after a restart.

**Comment by riskcapital** [comment]
I've shipped some updates to OSC in the latest versions, but I am reviewing this to make sure everything is solid.  I will message back when there is an update.

**Comment by riskcapital** [comment]
Both halves of this are now fixed, landing in the upcoming **2.0** release. Thanks for the precise report — and to @Hphone123, whose "it started working after about an hour with no config change" comment turned out to be the key clue.

**1. The OSC listener never started — because the toggle was invisible.**

This was not in the OSC stack at all. The Settings markup rendered the switch as `<span class="slider">` while the stylesheet defines `.toggle-slider`, and `.toggle input` sets `opacity: 0; width: 0; height: 0` to hide the native checkbox so the styled track can stand in for it. Net result: the checkbox was invisible *and* the track never rendered. There was nothing to see and no obvious affordance to click, so the listener was simply never enabled — which is exactly why the UDP port never opened and no packets arrived.

That also explains the "fixed itself after an hour" behaviour: the `<label>` still wrapped the input, so clicking the empty 48×26px region where the switch should have been did toggle it. Easy to hit by accident, impossible to hit on purpose.

The same bug was hiding the **Enable Keyboard Control** switch. The other 11 toggles in that panel already used the correct class, which is why this went unnoticed for so long.

**2. `prompt() is not supported`.**

Electron does not implement `window.prompt()`. OSC Learn had already been moved off it in an earlier update, but two rename paths still called it and were therefore dead in the desktop app:

- the VJ stage-preset context menu — which is a good illustration of the bug, since a fully working inline rename already existed on those same presets via double-click; the menu item was just a second, broken route to the same operation. It now opens that editor.
- SynthVision presets — no inline editor existed, so one was added following the same pattern used elsewhere in the app, plus double-click to rename.

There are now zero `prompt()` calls in the codebase. (`confirm()` is unaffected and still works — Electron implements `alert()` and `confirm()`, only `prompt()` is missing, which is why delete-confirm worked while rename did not.)

**After updating to 2.0:** Settings → Integrations → OSC, enable **Enable OSC Listener**, and the status should read "Listening on UDP 8000". The setting persists across restarts. If macOS or Windows prompts to allow incoming connections, allow it.

Closing as fixed on the release branch. Please do reopen if you still see anything once 2.0 is out.
